# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: rdkit_version
  displayName: Rdkit version (underscore format)
  type: string
- name: semver_version
  displayName: Sub-semver version of the npm package
  type: string
- name: beta
  displayName: Is beta?
  type: boolean
  default: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 20.10.5
    releaseType: stable
- script: |
    RDKIT_DASH_VERSION=${{ parameters.rdkit_version }} SEMVER_VERSION=${{ parameters.semver_version }}  BETA=${{ parameters.beta }} NPM_TOKEN=$(NPM_TOKEN) npm run build
  displayName: 'Build RDKit.js'
